import { PrismaClient } from '@prisma/client';
import argon2 from 'argon2';

const prisma = new PrismaClient();

async function main() {
  const schoolA = await prisma.tenant.upsert({
    where: { slug: 'flight-school-alpha' },
    update: {},
    create: { name: 'Flight School Alpha', slug: 'flight-school-alpha' },
  });
  const schoolB = await prisma.tenant.upsert({
    where: { slug: 'flight-school-beta' },
    update: {},
    create: { name: 'Flight School Beta', slug: 'flight-school-beta' },
  });

  const adminPassword = await argon2.hash('Admin123!', { type: argon2.argon2id });
  const userPassword = await argon2.hash('Password123!', { type: argon2.argon2id });

  const adminA = await prisma.user.upsert({
    where: { tenantId_email: { tenantId: schoolA.id, email: 'admin@schoolalpha.com' } },
    update: {},
    create: {
      tenantId: schoolA.id,
      email: 'admin@schoolalpha.com',
      passwordHash: adminPassword,
      role: 'ADMIN',
      approved: true,
    },
  });
  const instructorA = await prisma.user.upsert({
    where: { tenantId_email: { tenantId: schoolA.id, email: 'instructor@schoolalpha.com' } },
    update: {},
    create: {
      tenantId: schoolA.id,
      email: 'instructor@schoolalpha.com',
      passwordHash: userPassword,
      role: 'INSTRUCTOR',
      approved: true,
    },
  });
  const studentA = await prisma.user.upsert({
    where: { tenantId_email: { tenantId: schoolA.id, email: 'student@schoolalpha.com' } },
    update: {},
    create: {
      tenantId: schoolA.id,
      email: 'student@schoolalpha.com',
      passwordHash: userPassword,
      role: 'STUDENT',
      approved: true,
    },
  });
  const studentPendingA = await prisma.user.upsert({
    where: { tenantId_email: { tenantId: schoolA.id, email: 'pending@schoolalpha.com' } },
    update: {},
    create: {
      tenantId: schoolA.id,
      email: 'pending@schoolalpha.com',
      passwordHash: userPassword,
      role: 'STUDENT',
      approved: false,
    },
  });

  const adminB = await prisma.user.upsert({
    where: { tenantId_email: { tenantId: schoolB.id, email: 'admin@schoolbeta.com' } },
    update: {},
    create: {
      tenantId: schoolB.id,
      email: 'admin@schoolbeta.com',
      passwordHash: adminPassword,
      role: 'ADMIN',
      approved: true,
    },
  });
  const instructorB = await prisma.user.upsert({
    where: { tenantId_email: { tenantId: schoolB.id, email: 'instructor@schoolbeta.com' } },
    update: {},
    create: {
      tenantId: schoolB.id,
      email: 'instructor@schoolbeta.com',
      passwordHash: userPassword,
      role: 'INSTRUCTOR',
      approved: true,
    },
  });
  const studentB = await prisma.user.upsert({
    where: { tenantId_email: { tenantId: schoolB.id, email: 'student@schoolbeta.com' } },
    update: {},
    create: {
      tenantId: schoolB.id,
      email: 'student@schoolbeta.com',
      passwordHash: userPassword,
      role: 'STUDENT',
      approved: true,
    },
  });

  const course1 = await prisma.course.create({
    data: {
      tenantId: schoolA.id,
      title: 'Private Pilot Ground',
      description: 'Ground school for PPL',
      createdById: instructorA.id,
    },
  });
  const mod1 = await prisma.module.create({
    data: { courseId: course1.id, title: 'Aerodynamics', order: 0 },
  });
  await prisma.lesson.create({
    data: {
      moduleId: mod1.id,
      title: 'Lift and Drag',
      type: 'TEXT',
      content: 'Lift is generated by the wings...',
      order: 0,
    },
  });
  await prisma.lesson.create({
    data: {
      moduleId: mod1.id,
      title: 'Aerodynamics Quiz',
      type: 'QUIZ',
      content: JSON.stringify({
        questions: [
          {
            id: 'q1',
            text: 'What creates lift?',
            options: [
              { id: 'a', text: 'Engine' },
              { id: 'b', text: 'Wing shape and AOA' },
              { id: 'c', text: 'Rudder' },
            ],
            correctOptionId: 'b',
          },
        ],
      }),
      order: 1,
    },
  });

  // Schedule: instructor availability + sample booking for Flight School Alpha
  const nextWeek = new Date();
  nextWeek.setDate(nextWeek.getDate() + 7);
  const slotStart = new Date(nextWeek);
  slotStart.setHours(9, 0, 0, 0);
  const slotEnd = new Date(nextWeek);
  slotEnd.setHours(12, 0, 0, 0);
  await prisma.instructorAvailability.create({
    data: {
      tenantId: schoolA.id,
      instructorId: instructorA.id,
      startAt: slotStart,
      endAt: slotEnd,
    },
  });
  const bookStart = new Date(nextWeek);
  bookStart.setHours(10, 0, 0, 0);
  const bookEnd = new Date(nextWeek);
  bookEnd.setHours(11, 0, 0, 0);
  await prisma.booking.create({
    data: {
      tenantId: schoolA.id,
      studentId: studentA.id,
      status: 'REQUESTED',
      requestedAt: new Date(),
      startAt: bookStart,
      endAt: bookEnd,
    },
  });

  console.log('Seed complete:', {
    tenants: [schoolA.slug, schoolB.slug],
    users: { adminA: adminA.email, instructorA: instructorA.email, studentA: studentA.email },
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
